// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // ts: prisma config 需要 string，这里在未配置时回退为空串，避免编译期报错。
    url: process.env["DATABASE_URL"] ?? "",
  },
});
