// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // MySQL 是默认生产客户端；SQLite 使用 prisma/schema.sqlite.prisma 单独生成客户端。
    url: process.env["DATABASE_URL"] ?? "",
  },
});
